baseURL = "https://blog.moulard.org/"
languageCode = "fr"
title = "Moulard's Blog"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

# Site settings
theme = "hugo-theme-cactus-plus"
# googleAnalytics = "your_google_analytics_id"
# Set the value to true if your site include CJK (Chinese, Japanese, and Korean languages) characters
hasCJKLanguage = false

summaryLength = 10

linenos = true

[params]
	author = "La famille Moulard and co"
	description = "Site qui sert de blog pour les Moulard"
	bio = "La famille Moulard au grand complet !"

	linkedin = "https://linkedin.com/in/tommoulard"
	facebook = "tommoulard"

	enableRSS = true
	enableToc = true

	enableDisqus = true
	disqusShortname = "blog-moulard-org"

	enableSummary = true
	# Set the value to true if use description in post front matter replace content summary
	useDescriptionReplaceSummary = false

	enableGoogleAnalytics = false
	enableBaiduAnalytics = false
	# Set the value to your baidu analysis code if you want to use baidu analytics
	# baiduAnalytics = 'your_baidu_analysis_code'

	enableTwitterCard = true
	# The url for twitter card image, default is avatar.png in static/images directory
	twitterCardImage = ""

	# Add custom assets with their paths relative to the static folder
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = "S'abonner au flux RSS"

	olderPosts = ""
	newerPosts = ""
	copyright = ""

	# show latest posts in single page
	showLatestPosts = false
	readMore = ""

	# Share
	enableShare = true
	tweet = ""
	share = ""

	# 404 page
	title404 = "Désolé"
	subtitle404 = "Nous n'avons pas encore crée d'article là dessus"

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"

	# The social icons can be styled differently if you use mono as font - circle, rounded, or empty

	# Enable Git informations
	enableGitInfo = true

	socialIconStyle = ""
	[params.navigation]
		help = "Aide"


# Add additional social link entries underneath
[social]
	facebook-square = "https://www.facebook.com/tommoulard"
	rss-square = "/index.xml"
	github-square = "https://www.github.com/tommoulard"

[taxonomies]
	category = "categories"
	tag = "tags"

[related]
	threshold = 80
	includeNewer = true
	toLower = false

[markup]
  [markup.tableOfContents]
    endLevel = 8
    ordered = false
    startLevel = 1